name = "VegaStreams"
uuid = "10672a62-9285-4dfa-9c21-d72c3bde7b6c"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
